# .travis.yml
# vim: ai et ts=2 sw=2 sts=2 ft=yaml fenc=UTF-8
---
sudo: false
language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox

after_success:
- pip install codecov
- codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: maartenq
  password:
    secure: !!binary |
      V3daUUxpdDI2RkZNWHhFOFRtSjVoYitwZFNwMXVveitiVlpLSE5PajVHdUQwUXVadlZNcWNMOUow
      eEt3Mkk0RTZXNlpKMU5TSWJ3U2REbEVSOHJEY3FGZXJiaFZjQjM2d1l2MUhOdktZREorY3JyNFhq
      MW5kNDBxT2tOSkJHR0xES2JWelluU25GSXAwN09XZENFK2hSN0R1eUt5Z2VzdmpMaU4rZDd4VURE
      NXg1b3pyamp2ZitUSkE3bFh1SzE2Vjlnckt0SG4wdWVHUktLbmR0a2hiNHNZWHYvQUpyRkVtRmlS
      aW80WGRZVkVycU9JUmphSENtVnZ0MjByZ0lyejNqR21mNTY0R3crNDBDVnlKektJOVJUZDJiZUdM
      NE1wallzVlpaREJGdERRbEZqNU1qNExSU1k3SGFYaE0vQUVyaXZyeVZ3MlNHVXZ4TFlDR3BUUW1J
      YklpWW9RMW1jTFp2M2szajQ2ajVHU0tSUVk5NWNhMHlxcVM1QWc1Q1ZpWlhLVjV2NWZvOXVjVXBV
      eC9oTEcvSEY1UFYyTDduZlc2ZXdHeFFVay8vRFc2ekF1UkZCa3FjbHdZVmFVbTZha0t4SUVIcVAw
      eGpMNnFZb2RkL0hScWsxUVJqVTAyS05lL0dFSmJVUHhNQXA4RmtXdTJ4dHJFUll5V1d6TDlhdThD
      VWRVL3NFU2hyYWQxdmY0ZHpDclJPY0NjQ1VYK3BwSWt2L2RFdDBVdE5mc2Fwb0o0Q0FNQ2oxNEZ4
      WFNNSGFqVUI2eWZ3SlhERU5rOFVpTG0zb08wbWlxL2ZIWWNFWjBOMVgrUEZFbUM0VCtJdGxIUHlN
      SVpIYmpJL2dwelhwUXpVZzZuRkNjQk55czBOYzJBWHVubEp2SFlsUFluRng1eHUxdWxaQ2crcmM9
  "on":
    tags: true
    repo: maartenq/kiek
    condition: $TOXENV == py27
